name: build

on:
    push:
    schedule:
        - cron: '0 12 * * 0'

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.1', '7.4', '8.0']
                composer: ['--prefer-lowest', '']
                exclude:
                    - php: '8.0'
                      composer: '--prefer-lowest'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, json, mbstring, libxml
                  coverage: xdebug

            - name: Git checkout
              uses: actions/checkout@v2

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

            - name: Get Composer cache dir
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{steps.date.outputs.date}}-${{ runner.os }}-${{ matrix.php }}${{ matrix.composer }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{steps.date.outputs.date}}-${{ runner.os }}-${{ matrix.php }}${{ matrix.composer }}-composer-

            - name: Update Composer dependencies
              run: composer update ${{ matrix.composer }} --prefer-dist --no-progress --no-suggest --no-interaction
              if: matrix.php != '8.0'

            - name: Update Composer dependencies (ignore platform requirements)
              run: composer update ${{ matrix.composer }} --prefer-dist --no-progress --no-suggest --no-interaction --ignore-platform-reqs
              if: matrix.php == '8.0'
              # Ignore platform requirements for PHP 8. Not yet supported by all packages.

            - name: Run PHP Code Sniffer
              run: composer run-script test:phpcs
              if: success()

            - name: Run PHPStan
              run: composer run-script test:phpstan
              if: success() || failure()

            - name: Run PHPUnit with coverage
              run: composer run-script test:phpunit-coverage
              if: success() || failure()

            - name: Run Covelyzer
              run: composer run-script test:covelyzer
              if: success() || failure()

            - name: Run PHPBench
              run: composer run-script test:phpbench
              if: (success() || failure()) && matrix.composer != '--prefer-lowest' && matrix.php != '8.0'
              # Skip for prefer lowest as it throws error on PHP 7.4. See: https://bugs.php.net/bug.php?id=78482
              # Skip for PHP 8, not supported yet by PHPBench.
